apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: basic-cluster
  region: ap-south-1

nodeGroups:
  - name: ng-1
    instanceType: t2.micro # this is free tier
    desiredCapacity: 2
    privateNetworking: false
    ssh:
      allow: true
