apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel
  labels:
    app: laravel
spec:
    replicas: 1
    selector:
      matchLabels:
        app: laravel
    template:
      metadata:
        labels:
          app: laravel
      spec:
        containers:
        - name: frontend
          image: 888276918709.dkr.ecr.ap-south-1.amazonaws.com/frontend:latest
          ports:
          - containerPort: 80
            
          
          volumeMounts:
          - mountPath: /public_html
            name: glue-app

        - name: backend
          image: 888276918709.dkr.ecr.ap-south-1.amazonaws.com/backend:latest
          ports:
          - containerPort: 9000
          volumeMounts:
          - mountPath: /public_html
            name: glue-app
          
        - name: mysql
          image: mysql:5 
          env:
          - name: MYSQL_DATABASE
            value: laraveldb
          - name: MYSQL_USER
            value: laraveluser
          - name: MYSQL_PASSWORD
            value: laravrlpass 
          - name: MYSQL_ROOT_PASSWORD
            value: StongPass
          ports:
          - containerPort: 3306
          
          volumeMounts:
          - mountPath: /var/lib/mysql
            name: glue-db-vol

        volumes:
        - name: glue-app
        - name: glue-db-vol
---
apiVersion: v1
kind: Service
metadata:
  name: laravel-service
spec:
    selector:
      app: laravel
    ports:
    - protocol: TCP
      port: 80
      targetPort: 80
    type: LoadBalancer
